pipeline {
    agent any

    stages {
        stage("Build Backend") {
            steps {
                dir("backend") {
                    sh "mvn clean install -Pdev -DskipTests"
                }
            }
        }

        stage("Build Frontend") {
            steps {
                dir("frontend") {
                    sh "npm install"
                    // kein npm run build mehr, weil statisches HTML
                }
            }
        }

        stage("Test Backend") {
            steps {
                dir("backend") {
                    sh "mvn test -Pdev"
                }
            }
        }

        stage("Test Frontend") {
            steps {
                dir("frontend") {
                    sh "npm test"
                }
            }
        }

        stage("Docker Build") {
            steps {
                script {
                    sh "docker build -t skyerededucation.azurecr.io/abschlussprojekt-backend:latest -f backend/Dockerfile ./backend"
                    sh "docker build -t skyerededucation.azurecr.io/abschlussprojekt-frontend:latest -f frontend/Dockerfile ./frontend"
                }
            }
        }

        stage("Docker Push") {
            steps {
                script {
                    sh "docker push skyerededucation.azurecr.io/abschlussprojekt-backend:latest"
                    sh "docker push skyerededucation.azurecr.io/abschlussprojekt-frontend:latest"
                }
            }
        }

        stage("Deploy Dev") {
            steps {
                script {
                    sh "kubectl apply -f kubernetes/frontend-deployment-dev.yaml --namespace=denizcan-dev"
                    sh "kubectl apply -f kubernetes/frontend-service-dev.yaml --namespace=denizcan-dev"
                    sh "kubectl apply -f kubernetes/backend-deployment-dev.yaml --namespace=denizcan-dev"
                    sh "kubectl apply -f kubernetes/backend-service-dev.yaml --namespace=denizcan-dev"
                }
            }
        }

        stage("Manual Approval") {
            steps {
                script {
                    input message: "Soll das Deployment in Prod gestartet werden?", ok: "Ja, weiter mit Prod"
                }
            }
        }

        stage("Deploy Prod") {
            steps {
                script {
                    sh "kubectl apply -f kubernetes/frontend-deployment-prod.yaml --namespace=denizcan-prod"
                    sh "kubectl apply -f kubernetes/frontend-service-prod.yaml --namespace=denizcan-prod"
                    sh "kubectl apply -f kubernetes/backend-deployment-prod.yaml --namespace=denizcan-prod"
                    sh "kubectl apply -f kubernetes/backend-service-prod.yaml --namespace=denizcan-prod"
                }
            }
        }
    }
}
